{
  "exception_throw": [
    {
      "evaluation_item": "完整度->单应用跟踪完整度->异常与错误处理->异常抛出和捕获",
      "scene_levels": [
        {
          "level": "2+",
          "scene_list": [
            {
              "compose": "exception_try_001_T.py && !exception_try_002_F.py",
              "scene": "exception_try"
            },
            {
              "compose": "exception_catch_001_T.py && !exception_catch_002_F.py",
              "scene": "exception_catch"
            },
            {
              "compose": "exception_try_else_001_T.py && !exception_try_else_002_F.py",
              "scene": "exception_try_else"
            },
            {
              "compose": "exception_finally_001_T.py && !exception_finally_002_F.py",
              "scene": "exception_finally"
            }
          ]
        }
      ]
    }
  ]
}